# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adamsandwich blog
author: Adamsandwich
email: adamsandwich@outlook.com
keyword: "adamsandwich, Adamsandwich Blog, 博客, 个人网站, 互联网, Web"
description: >- # this means to ignore newlines until "baseurl:"
  I`m a full stack engineer which means if you give me one more task my stack will overflow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adamsandwich.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username: adamsandwich

# Build settings
sass:
  sass_dir: _scss
  style: compressed
toc:
  list_class: toc
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
paginate: 5
plugins: [jekyll-paginate, jekyll-toc]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
