name: Deploy

on:
  push:
    branches:
      - nuxt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nuxt
        uses: actions/checkout@v2
        with:
          ref: nuxt
          lfs: true

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Build project
        run: yarn && yarn generate && yarn minify


      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: './dist/*'
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.REMOTE_PATH }}
          ARGS: "-avzr --delete"
