name: Deploy

on:
  push:
    branches:
      - nuxt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout nuxt
        uses: actions/checkout@v2
        with:
          ref: nuxt

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Build project
        run: yarn && yarn generate && yarn minify

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: ${{ secrets.USERNAME }}
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: ${{ secrets.REMOTE_PATH }}
          args: '-o ConnectTimeout=5'
